### ISSUE TITLE
Second comparison round

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParserComparison#1]
Hello together,

since my initial commit in [UserAgentParser](https://github.com/ThaDafinser/UserAgentParser), i improved a lot of things
I think it's now in a pretty stable state, but there will be still wrong implementations or wrong "positives".

I also splitted the comparison from the UserAgentParser to this repository.
So the UserAgentParser can be used indepent from this (really ugly) code.

I think this comparison is a good source, to improve each provider.

The results currently include:
- a detail page with the total numbers of the different results
- a "not found" log, with the results found from the other providers

I also added a lot of test data suites from different vendors:
- donatj
- piwik
- whichbrowser
- yzalis

[Go to the results](http://thadafinser.github.io/UserAgentParserComparison/)

Improving the comparison results further will be one of the next steps.
Since we could gather there a lot more information
- find "wrong positives" (results witch are wrong)
- find all missing matches
- ...

I hope the early `not found log`, maybe help you to improve your already good UserAgent parsers.

I would be also happy about feedback/ideas for the comparison or my implementation of your parser in [UserAgentParser](https://github.com/ThaDafinser/UserAgentParser)

//cc 
@mimmi20
@donatj
@sgiehl
@lstrojny 
@NielsLeenheer
@yuya-takeyama
@blaugueux

**Comment by mimmi20** [comment]
@ThaDafinser When do you add a useragent to your `not found log`?

**Comment by ThaDafinser** [comment]
Currently only when there is completely no result. This could also be splitted into no OS, no device,... result.

**Comment by mimmi20** [comment]
It would be nice if in the `not found list` an notice was added how many useragents are in the list.

**Comment by mimmi20** [comment]
Feel free to open issues for the not found useragents on browscap/browscap. Please do not add more than 100 useragents at once. into a ticket.

**Comment by ThaDafinser** [comment]
I just published a complete new version, with a lot of new insights and reports http://thadafinser.github.io/UserAgentParserComparison/results/index.html

Note: It seems i used the wrong browscap file, thats why no bots are detected...i will it later

**Comment by ThaDafinser** [comment]
The provider view has now a lot of improvements, to get more insights

Which browser, engines, operating systems or devices are detected and many more.

Example

![image](https://cloud.githubusercontent.com/assets/533017/11301967/caf9a6b0-8f9a-11e5-926c-b01b51e769d8.png)
