### ISSUE TITLE
The gh-pages branch is used for development

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#11]
Just a small nitpick :grimacing:

**Comment by ThaDafinser** [comment]
Yep..i will split that if all is like i want it :+1: 

In the meantime i need to host somewhere the (new) database...with your millions of records the database cannot be sqlite anymore :smile: 

@NielsLeenheer do you know maybe a good cloud database?
Amazon RDS only have 10 million E/A for free, which will be too low https://aws.amazon.com/de/rds/free/

**Comment by ThaDafinser** [comment]
solved now :-)
