### ISSUE TITLE
Some strings which are classified as bots are not really bots

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#18]
It looks like the browscaps testsuite classifies many regular user agent strings as bots. This also means they end up in the "Not detected as bot" page. 

In each of these case the name of the bot starts with "Fake", like "Fake IE" or "Fake Chrome". Some of them are perfectly normal browser user agent strings and the testsuite is just wrong and while others may indeed not be IE or Chrome, there is no reason to believe they are actually a bot. They are as most suspicious.

It may be a good idea to not consider both that start with the name "Fake" as bots.

For example:
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/0b/76/0b76bc41-758e-4d4f-942c-324ce27966e2.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/15/72/15728289-eb23-4593-997e-7cee4abf702e.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1a/15/1a156493-31e3-4cbb-bc23-324c3ff7f0aa.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1c/f9/1cf953f5-22b2-4c99-a7c7-7ded6390da70.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1f/a3/1fa3fa8c-1a43-44c0-a320-9666c1584043.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/23/40/2340930a-e2b5-468c-bbb5-808c0dd43f7b.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/2e/77/2e776fdf-8896-4fd7-9ac0-b7f7c57c59b8.html
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/f3/f8/f3f80110-1f50-4d6a-b2d1-bd96c63491c6.html

**Comment by mimmi20** [comment]
@NielsLeenheer I viewed these pages. Here are my comments

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/0b/76/0b76bc41-758e-4d4f-942c-324ce27966e2.html
- I have to review this result

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/15/72/15728289-eb23-4593-997e-7cee4abf702e.html
- This Chrome-UA starts with `Mozilla/4`, it should start with `Mozilla/5` (maybe I'm wrong here)

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1a/15/1a156493-31e3-4cbb-bc23-324c3ff7f0aa.html
- The token `Trident/5.0` is missing. This token is required for IE 9 (I understand this page this way https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx)
- The IE 9 useragent should start with `Mozilla/5.0` (maybe I'm wrong here)

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1c/f9/1cf953f5-22b2-4c99-a7c7-7ded6390da70.html
- The UA starts with `Mozilla/6`

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1f/a3/1fa3fa8c-1a43-44c0-a320-9666c1584043.html
- A space is missing between `Mac` and `OS`

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/23/40/2340930a-e2b5-468c-bbb5-808c0dd43f7b.html
- The UA starts with Quotes.

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/2e/77/2e776fdf-8896-4fd7-9ac0-b7f7c57c59b8.html
- This Firefox-Mobile-UA includes a wrong Gecko token (see here https://developer.mozilla.org/de/docs/Gecko_user_agent_string_referenz) 
- The Gecko version should be the same as the Firefox version

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/f3/f8/f3f80110-1f50-4d6a-b2d1-bd96c63491c6.html
- This UA wants to be an IE and a Netscape Browser. This should not be valid.

**Comment by NielsLeenheer** [comment]
I'm not saying there not something weird with these user agent strings. There probably is. What I'm saying is that 'it is a bot' is not necessarily the best explanation. At least not a good enough an explanation to say it undoubtably is a bot for the purposes of comparing results.

What I've found (by looking at the raw data from html5test.com) is that most of these small deviations from expected formats are actually browsers. They are not always from the browser they claim to be, but browsers nonetheless. And I can tell by looking at a fingerprint created based on more than a hundred feature detection tests and compare it with fingerprints from known browsers. From that fingerprint I can detect a browser with extremely good accuracy without even looking at the user agent string.

Possible explanations can be:
- Experimentation by browser developers
- Corruption of the header by faulty proxies (or however it is stored before it gets analysed)
- User agent switchers
- Users editing the user agent themselves
- Or maybe a bot

Classifying them as suspicious or fake may be warranted. But not as a bot.

Some specific responses:

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/0b/76/0b76bc41-758e-4d4f-942c-324ce27966e2.html
- This is identical to the user agent string shown on this page: https://blogs.msdn.microsoft.com/ie/2011/04/15/the-ie10-user-agent-string/

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/23/40/2340930a-e2b5-468c-bbb5-808c0dd43f7b.html
- This is most likely corruption along the way, like a proxy

http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/f3/f8/f3f80110-1f50-4d6a-b2d1-bd96c63491c6.html
- Netscape 8 had an "IE mode", which allowed you to use the IE rendering engine inside of Netscape 8.

**Comment by ThaDafinser** [comment]
@NielsLeenheer @mimmi20 detecting it as bot is wrong, but it could be actually also wrong to detect it as a normal browser (without the background check you have from html5test.com)

So i will exclude tests from `browscap` which contain `Fake` in the next test run. (77 user agents in total)

Is that fine?

![image](https://cloud.githubusercontent.com/assets/533017/13042755/f43b0746-d3c2-11e5-8326-c5b7bdce7c28.png)

**Comment by ThaDafinser** [comment]
see https://github.com/ThaDafinser/UserAgentParserComparison/pull/20

**Comment by NielsLeenheer** [comment]
:+1:

**Comment by ThaDafinser** [comment]
Merged #20
