### ISSUE TITLE
Not detected list of models contain generic expectations

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#19]
I don't think generic model names should be counted as a positive identification of the model of a device, because it is just placeholder that is used, because the model could not be identified. Including these generic models would unfairly show libraries using generics to have a better rate of model identification than they really have.

**BrowscapPhp** uses these generic names as device model:

"Windows desktop"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/4f/0c/4f0c603a-fd1c-4af9-bed7-ab2567cffd03.html

"Linux desktop"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/ad/4f/ad4f456b-6a94-41ab-ab0a-2548367d9821.html

**WhatIsMyBrowserCom** uses these generic names as device model: 

"Android Phone"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/cd/91/cd9123c5-e233-4524-921e-c331e176b07a.html

"Android Tablet"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/2b/3d/2b3d152e-90cf-403a-bf4b-cb235f67e045.html

"Windows Phone 7"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/14/35/14354ed0-269f-45dd-a115-cae6c6edacbe.html

**NeutrinoApiCom** uses these generic names as device model: 

"Windows Mobile"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/09/7b/097b57f4-69ad-4400-8fdf-f6dd89c04680.html

"Windows Mobile (Opera)"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/20/1b/201b22d7-a92f-4725-814d-5653ec2d339b.html

"Windows Phone 7"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/df/ed/dfed047e-1b64-408b-a673-f52c542f92b3.html

"Windows Phone 7.5"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/00/34/0034ddf7-43df-4fca-8e6d-696709ca9df0.html

"Windows Phone 8"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/01/05/0105f8f2-ab58-4b4b-9925-53eca590eae4.html

"Firefox OS"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/20/9c/209ccaeb-eb56-473d-916f-7e44cb77ca2a.html

"Firefox for Android"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/27/2a/272a07c1-ecc5-4e4a-b36c-af1328b0498b.html

"Firefox Mobile"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/6b/ae/6bae4c46-7ce9-409d-88d1-8963e805b76d.html

"Mobi for Android"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/2d/85/2d85be79-1658-4e17-9734-084a0fdb3470.html

"Tablet on Android"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/2d/85/2d85be79-1658-4e17-9734-084a0fdb3470.html

"Opera Mini for S60"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/1e/2e/1e2e5eed-a8a8-4659-a39c-7e0675e6f118.html

"Opera for Series 60"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/39/af/39afd041-5d96-40b7-afb6-4f5a4e91f7d2.html

"Opera"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/17/8a/178a9f52-070f-4ddb-bd90-26b9b2398a1a.html

"Generic Maemo with Fennec"
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/80/cb/80cbb8a8-1c52-4a44-a674-bcafdb150698.html

It looks like many of these cases actually have the same Brand name: "Generic", "Opera", "Opera Software" or "Mozilla", so that may be a way to filter them.

**Comment by mimmi20** [comment]
@NielsLeenheer @ThaDafinser We also have als Generic Devices Types for Mobile devices.
@ThaDafinser It looks like you are mapping the browser type from NeutrinoApiCom as device type into your results. I found `mobile-browser`, `email-client` and `desktop-browser` as device types. Also the engine and the OS data are switched in the result for WhichBrowser and WhatIsMyBrowserCom.

**Comment by ThaDafinser** [comment]
@mimmi20 

> @ThaDafinser It looks like you are mapping the browser type from NeutrinoApiCom as device type into your results. I found mobile-browser, email-client and desktop-browser as device types

i don't map the browser type from `NeutrinoApiCom` to the device type, it's the type actually. Maybe i need to split it a bit more.
https://www.neutrinoapi.com/api/user-agent-info/
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/Http/NeutrinoApiCom.php#L255-L256

> Also the engine and the OS data are switched in the result for WhichBrowser and WhatIsMyBrowserCom.

Can you show me the link?

## About generics ...

### General

This is currently the "hottest" and most difficult thing to solve IMO.
I'm in general :+1: with @NielsLeenheer , that it should not be counted as a positive result.

But I'm currently also not sure how and there we should solve it....here are some thoughts.
- UserAgentParserComparison should show unmodified results from UserAgentParser abstraction 
  - so you know what u get from the abstraction result at the end
  - to verify the abstraction layer is correct (especiall for me an important test)
- the generics listed above are dynamic, this means
  - new one will appear
  - we will never cover all
  - at some point a generic (could) become a valid model
    - someone may release a phone called Opera? (may never happen, but it's possible)
  - generics are currently around in different result parts

Those are my general thoughts about it.

#### Possible solutions 1)

I detect and remove the generics with the UserAgentParser abstraction, like done for some defaultValues already
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/BrowscapPhp.php#L64-L69
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/PiwikDeviceDetector.php#L64-L70

**_Pro**_
- also a good thing ("buy argument") for the abstraction layer itself (UserAgentParser)

**_Con**_
- add complexity to the (currently thin) abstraction layer
- someone needs to maintain that list for each provider
- possibly remove real detected values in the future (Opera example above)

#### Possible solutions 2)

Remove the generics only for the comparison here. So the abstraction layer still return those values

**_Pro**_
- abstraction layer stays thin (UserAgentParser)

**_Con**_
- the result from the comparison is different to the abstraction layer
- someone needs to maintain that list for each provider
- possibly remove real detected values in the future (Opera example above)

#### Possible solutions 3)

Encourage (and teach/help) the parser vendors to get rid of those defaults values and generics.

**_Pro**_
- the vendor improve their parser
- comparison does not need extra complexity

**_Con**_
- long term only
- not all vendors will change it

#### Possible solutions 4)

Leave it "as is"

**_Pro**_
- with the `quality medals` it may not be that important anymore
- comparison does not need extra complexity

**_Con**_
- detection percentage can not be really compared (no true numbers)

### Summary

Solution 3) can be done regardless, if we "implement" 1) 2) or 4).

I dont' know if 1) 2) or 4) is better.

What you guys think?

**Comment by NielsLeenheer** [comment]
Regarding 3): I'm not against generics by definition. It is perfectly fine to use a generic as a placeholder if you want to present data to the user. But for both UserAgentParser and UserAgentParserComparison I don't think generics should be used. A way to solve it for each individual library is perhaps to add a flag when a generic is used. But like you said, this won't be a short term solution, if we can accomplice this at all.

I'd say 4) is not really desirable too. The problem is not just that it makes one or the other library look better. It also pollutes the overviews. If you look at [this one](http://thadafinser.github.io/UserAgentParserComparison/v4/not-detected/WhichBrowser/device-models.html) you can see it is very difficult to find things to fix, because the overwhelming number of generics in there.

So maybe 1) or 2) is the best solution at this time. 

And I think I prefer 1) because it is already is filtering for generics and it will improve the quality of the results not only for this project, but for every project that is using UserAgentParser.

**Comment by NielsLeenheer** [comment]
> > Also the engine and the OS data are switched in the result for WhichBrowser and WhatIsMyBrowserCom.
> 
> Can you show me the link?

I think this is the same as bug #21

**Comment by mimmi20** [comment]
@ThaDafinser The links are
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/6b/ae/6bae4c46-7ce9-409d-88d1-8963e805b76d.html (row with Source)
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/01/05/0105f8f2-ab58-4b4b-9925-53eca590eae4.html (row with source)
- http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/4f/0c/4f0c603a-fd1c-4af9-bed7-ab2567cffd03.html (row with source, engine name is missing too)

The switch is in the row with the source data (see #21). I dont find any other switched data.

**Comment by ThaDafinser** [comment]
I will check all the issues with label or switched values and fix it also for v4.

Just found that some generics for `Wurfl` are already replaced
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/Wurfl.php#L142-L165

Continue the work of generics solutions here https://github.com/ThaDafinser/UserAgentParser/issues/58

**Comment by ThaDafinser** [comment]
@mimmi20 @NielsLeenheer i have rewritten the filtering in the PR here https://github.com/ThaDafinser/UserAgentParser/pull/59/files

Next step: I fill again my local database with the **_unfiltered**_ results for each user agent and provider.
Then i will export a list for each provider, for each value like the browser names
http://thadafinser.github.io/UserAgentParserComparison/v4/detected/BrowscapPhp/browser-names.html

Then we can rebuild the regexes from the unfiltered results and compare it with the next resultset, so that everything will be correct.

**Comment by NielsLeenheer** [comment]
:+1:

**Comment by ThaDafinser** [comment]
PR for all local providers are ready for a review: https://github.com/ThaDafinser/UserAgentParser/pull/59

I will check later the results of the 3 HTTP providers

**Comment by ThaDafinser** [comment]
PR was merged https://github.com/ThaDafinser/UserAgentParser/pull/59

**Comment by ThaDafinser** [comment]
We can do another filtering, after the next comparison round!

But only about generics and not parse errros or wrong values - JUST generics
