### ISSUE TITLE
Complete detection results for all ua strings for all libraries

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#2]
I'd love to get the full results back from the first released version. Those tables were very unwieldy, but contained lots of useful data for improving our libraries. In fact, I've already used that version to fix a lot of detection errors.

**Comment by ThaDafinser** [comment]
I can "readd" them for sure. Need some time to get a better result comparison with more lists and insights.

In the meantime i added http://useragent.mkf.solutions to view UA results live

**Comment by ThaDafinser** [comment]
@NielsLeenheer just released a new version. There are a lot of new details in it

You can view it here: http://thadafinser.github.io/UserAgentParserComparison/results/index.html

I hope all is in it :smile:

**Comment by NielsLeenheer** [comment]
Whoooo! This looks really nice!

**Comment by ThaDafinser** [comment]
Thank you :smile:  i hope you get now more insights...but still much work to be done.
