### ISSUE TITLE
Browscap: No bots detected

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParserComparison#5]
Somehow browscap did not detected bots, which must be a failure.

I generated the cache with 

```
vendor/bin/browscap browscap:update
```

How can i generate it with the full browscap ini? I dit not found it here https://github.com/browscap/browscap-php

//ping @mimmi20

http://thadafinser.github.io/UserAgentParserComparison/results/index.html

**Comment by mimmi20** [comment]
Please open Tickets at `browscap/browscap-php` to add this to the documentation, and at `browscap/browscap` with the list of useragents.

**Comment by ThaDafinser** [comment]
I opened a ticket there about the full cache generation.

The comparison is updated with the full browscap file: http://thadafinser.github.io/UserAgentParserComparison/results/index.html

I wont report "not detected" useragents, since this would take too much time for each parser.
If someone wants to improve the implementation somewhere, it can be taken from the results of course.
