### ISSUE TITLE
Add switch to "Not found" report to hide entries which do not have any detected results

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#8]
Add a switch on the "Not found" reports that hides entries where none of the libraries find a result.

For example, there may be many result in the "Not found" report when there is actually nothing to detect. That is interesting in itself, but it may be more interesting to see where others do detect something, but one library does not.

**Comment by ThaDafinser** [comment]
Should be solved in the latest release
